### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by sascham** [DmitryRyumin/OIDv6#2]
pip install can search the package but not find it to install.

**Comment by DmitryRyumin** [comment]
> pip install может искать пакет, но не находить его для установки.

Hello! Do you install it from [oidv6](https://pypi.org/project/oidv6/) here? Everything has to be installed

**Comment by sascham** [comment]
![image](https://user-images.githubusercontent.com/277868/99516707-143e8280-29c1-11eb-98aa-4a36be806646.png)

**Comment by DmitryRyumin** [comment]
What version of python?

**Comment by sascham** [comment]
Version 3.6.8 on CentOS 8

**Comment by DmitryRyumin** [comment]
> Version 3.6.8 on CentOS 8

Then everything is clear! Please see the description! The minimum version of Python is 3.7. Create a new environment with version 3.7 and you will be happy.

![Example](https://raw.githubusercontent.com/DmitryRyumin/OIDv6/master/Iss/2.png)

**Comment by sascham** [comment]
thanks will try :)
