### ISSUE TITLE
multiple classes in each label

### ISSUE THREAD

**Issue by MrOCW** [DmitryRyumin/OIDv6#4]
Hi @DmitryRyumin ,

Is it possible to have an image and corresponding label with multiple unique classes?

For example
labelA.txt
Person X1 Y1 X2 Y2
Person X1 Y1 X2 Y2
Chair X1 Y1 X2 Y2
Chair X1 Y1 X2 Y2

**Comment by DmitryRyumin** [comment]
HI @MrOCW, 

Unfortunately, this functionality is not provided! The idea is great! Perhaps there will be support in the future.
